# Generated by Django 3.2.9 on 2021-11-28 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('autores', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=200)),
            ],
        ),
    ]
